# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: Your New Jekyll Site
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-babel
  - octopress-autoprefixer
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude

